### ISSUE TITLE
Fixed Files don't appear anymore / HTML Crashes

### ISSUE THREAD

**Issue by godvader8** [marcin-przywoski/Facebook-Export-Viewer#43]
I love your app, it saved me a lot of time, but it stopped working with the new version or something needs to be changed. 
It crashes on html, it processes json, but the files do not appear. 
I tested that it works fine with old json files downloaded half a year ago.
Could you fix this or tell me what I'm doing wrong?
Kinds regards

**Comment by marcin-przywoski** [comment]
Hello!

Facebook changes the schema from time to time. I need to have a look at what's changed and update the code. Gimme a day or two to fix that.

**Comment by godvader8** [comment]
Thank you.
You are doing a fantastic work!

wt., 30 sty 2024 o 11:53 Marcin Przywóski ***@***.***>
napisał(a):

**Comment by marcin-przywoski** [comment]
Small update from me - I didn't have a lot of time to have a look a this yet but I will over the weekend.

**Comment by godvader8** [comment]
Thank you for the information, I can't wait :)

pon., 5 lut 2024, 22:50 użytkownik Marcin Przywóski <
***@***.***> napisał:

**Comment by godvader8** [comment]
How's progress going? :)

pon., 5 lut 2024, 22:50 użytkownik Marcin Przywóski <
***@***.***> napisał:

**Comment by marcin-przywoski** [comment]
So the update from me is that it's trickier than I expected it to be. The actual .html structure didn't change that much but now Facebook doesn't include information about the export language unless specified explicitly in the request so I had to think how we can go around that. I found one solution and today I got it working so I'll try to release it during the weekend. It will be bundled with some UI changes but since I didn't have enough time to finish them they can be rough around the edges fyi

**Comment by marcin-przywoski** [comment]
@godvader8 you can now check the latest release, should be working now.

**Comment by godvader8** [comment]
Thank you very much!
It works, but unfortunately not everything, Facebook has enabled the
encryption function and some chats appear in the path
your_activity_across_facebook\messages\e2ee_cutover.
All photos, videos and chats are uploaded there, but ExportViewer does not
detect them.
I just copied the folders from e2ee_cutover to the inbox so that both
folders have the same copies, then ExportViewer detects them but not
everything. The program has a problem especially with photos, many are
missing.
Any idea how to fix this?


pon., 19 lut 2024 o 11:00 Marcin Przywóski ***@***.***>
napisał(a):

**Comment by godvader8** [comment]
Update:
From what I see, it's not the encryption's fault.
Folders that were in the inbox from the beginning also lose photos.

pon., 19 lut 2024 o 11:00 Marcin Przywóski ***@***.***>
napisał(a):

**Comment by marcin-przywoski** [comment]
@godvader8 - Ok, when I made an export I didn't see this folder and hence why I've not added it to the application. Give me a few hours to fix that. It's possible that the photos are not in the messages files. Can you tell where do you think the media in this folder are coming from?

**Comment by godvader8** [comment]
I checked carefully and the photos are in the conversations when the
message_1.html file is opened.  Basically, in a conversation with everyone
there are about 10-15% of photos missing, videos are complete.  I think I
found out what the problem is.  The problem is with photos when several of
them are sent in one message, they simply have one sent date. Instead of
all of them, it dumps only one of them in a folder. I don't remember this
problem occurring in previous versions.
Kind regards!

wt., 20 lut 2024, 13:59 użytkownik Marcin Przywóski <
***@***.***> napisał:

**Comment by marcin-przywoski** [comment]
I know what the problem is, at the moment application only gets the 1st element with image tag (but so is the same for other media types) instead of every element with such tag. I'll try to post a fix to that today

**Comment by godvader8** [comment]
Finally everything works, fantastic job, thank you very much! Is there any
way I can support your work?

wt., 20 lut 2024, 17:07 użytkownik Marcin Przywóski <
***@***.***> napisał:

**Comment by marcin-przywoski** [comment]
You're welcome!

Wow, to be honest I never thought about that. Maybe in the future once I'll expand the application a little bit, as of now I'd not feel good with getting money for application with very limited functionality

**Comment by godvader8** [comment]
You are very humble. Thank you again for your help.
I have one more problem that I can't deal with. Maybe you can help.
I wanted to download all videos from a public profile on Facebook (it's a
regional television). Is there any solution to this (preferably with
publication dates)? I tried to download them individually, but it is
tedious work and you have to insert the dates manually. Do you have any
idea?

pon., 26 lut 2024 o 00:18 Marcin Przywóski ***@***.***>
napisał(a):

**Comment by marcin-przywoski** [comment]
Hmmm it's certainly doable in code with Selenium Webdriver or something similar but you also might be able to do that with a RPA tool like the free Power Automate.
